version: "3.5"
services:
  idp:
    image: lucidprogrammer/saml_idp:local
    container_name: idp
    environment:
      - "adminpassword=${IDP_ADMINPASSWORD}"
      - "technicalcontact_name=${IDP_TECHCONTACT}"
      - "technicalcontact_email=${IDP_TECHEMAIL}"
      - "SP_HOST=http://${ROOTDOMAIN}"
      - "SP_PUBLIC_KEY=${SP_PUBLIC_KEY}"
    networks:
      - example_network
    # just being explicit, the idp container just exposes port 80, cannot access directly from host
    expose:
      - "80"
    command: ["apache2-foreground"]
    labels:
        - traefik.enable=true
        - traefik.port=80
        - traefik.frontend.rule=Host:${IDP_SUBDOMAIN}.${ROOTDOMAIN};PathPrefix:/saml
        - traefik.docker.network=example_network
    # deploy is only meant for docker swarm, it will not get picked up if you use docker-compose
    deploy:
      labels:
          - traefik.enable=true
          - traefik.port=80
          - traefik.frontend.rule=Host:${IDP_SUBDOMAIN}.${ROOTDOMAIN};PathPrefix:/saml
          - traefik.docker.network=example_network
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
  
    
networks:
  example_network:
    external: true