version: "3.5"
services:
    traefik:
      image: traefik:v1.7.12-alpine
      container_name: traefik
      command: -c --docker=true
          --docker.watch=true
          --web=true
          --debug=true
          --defaultEntryPoints='http'
          --entryPoints='Name:http Address::80'
      ports:
          - 80:80
          # - 8080:8080
      volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
      networks:
        - example_network
      deploy:
          placement:
              constraints: [node.role == manager]
networks:
  example_network:
    external: true